pipeline{
    agent{
        label "node"
    }
    stages{
        stage("A"){
            steps{
                echo "========executing A========"
                aws configure
                sh 'pwd'
                sh 'ls'
                docker build -t muy_first_image LLLLLLLL
                kubectl create -f LLLLLLLLL.yml
                kubectl apply -f kaslfajsdklfsaj.yml
                terraform init 
                terraform plan
                terraform apply
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}